Resolve bundle install error
Command `bundle _2.6.6_ install --verbose` results in an error indicating one of the following issues:
- `gumbo.c:32:10: fatal error: 'nokogiri_gumbo.h' file not found` while `Building Nokogiri with a packaged version of libgumbo-1.0.0-nokogiri.`
- `An error occurred while installing nokogiri (1.18.5), and Bundler cannot continue.`

Add x86_64 platforms to resolve this error, detailed below:

```
Installing minima 2.5.1
2:  jekyll-theme-time-machine (0.2.0) from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/specifications/jekyll-theme-time-machine-0.2.0.gemspec
0:  minima (2.5.1) from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/specifications/minima-2.5.1.gemspec
3:  jekyll-theme-midnight (0.2.0) from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/specifications/jekyll-theme-midnight-0.2.0.gemspec
Bundler::InstallError: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/ext/nokogiri
/usr/local/rvm/rubies/ruby-3.3.4/bin/ruby extconf.rb
checking for whether -std=c99 is accepted as CFLAGS... no
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... no
checking for whether -O2 is accepted as CFLAGS... no
checking for whether -g is accepted as CFLAGS... no
checking for whether -Winline is accepted as CFLAGS... no
checking for whether -Wmissing-noreturn is accepted as CFLAGS... no
checking for whether -Wconversion is accepted as CFLAGS... no
Building nokogiri using packaged libraries.
Static linking is enabled.
Cross build is disabled.
Using mini_portile version 2.8.8
checking for iconv... yes
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libxml2-2.13.6.
Configuration options: --host\=x86_64-pc-linux --enable-static --disable-shared --libdir\=/workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/ports/x86_64-linux/libxml2/2.13.6/lib --with-legacy --with-iconv\=yes --disable-dependency-tracking --without-python --without-readline --with-c14n --with-debug --with-threads --disable-shared --enable-static CPPFLAGS\= CFLAGS\=-O2\ -g\ -fPIC
The following patches are being applied:
  - 0001-Remove-script-macro-support.patch
  - 0002-Update-entities-to-remove-handling-of-ssi.patch
  - 0009-allow-wildcard-namespaces.patch
  - 0010-update-config.guess-and-config.sub-for-libxml2.patch
  - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
  - 0019-xpath-Use-separate-static-hash-table-for-standard-fu.patch

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

  https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

Note, however, that nokogiri cannot guarantee compatibility with every
version of libxml2 that may be provided by OS/package vendors.

Extracting libxml2-2.13.6.tar.xz into tmp/x86_64-pc-linux/ports/libxml2/2.13.6... OK
Running git apply with /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/patches/libxml2/0001-Remove-script-macro-support.patch... OK
Running git apply with /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/patches/libxml2/0002-Update-entities-to-remove-handling-of-ssi.patch... OK
Running git apply with /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/patches/libxml2/0009-allow-wildcard-namespaces.patch... OK
Running git apply with /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/patches/libxml2/0010-update-config.guess-and-config.sub-for-libxml2.patch... OK
Running git apply with /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/patches/libxml2/0011-rip-out-libxml2-s-libc_single_threaded-support.patch... OK
Running git apply with /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/patches/libxml2/0019-xpath-Use-separate-static-hash-table-for-standard-fu.patch... OK
Running 'configure' for libxml2 2.13.6... OK
Running 'compile' for libxml2 2.13.6... OK
Running 'install' for libxml2 2.13.6... OK
Activating libxml2 2.13.6 (from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/ports/x86_64-linux/libxml2/2.13.6)...
Using mini_portile version 2.8.8
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libxslt-1.1.43.
Configuration options: --host\=x86_64-pc-linux --enable-static --disable-shared --libdir\=/workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/ports/x86_64-linux/libxslt/1.1.43/lib --disable-dependency-tracking --without-python --without-crypto --with-debug --with-libxml-prefix\=/workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/ports/x86_64-linux/libxml2/2.13.6 --disable-shared --enable-static CFLAGS\=-O2\ -g\ -fPIC
The following patches are being applied:
  - 0001-update-config.guess-and-config.sub-for-libxslt.patch

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

  https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

Extracting libxslt-1.1.43.tar.xz into tmp/x86_64-pc-linux/ports/libxslt/1.1.43... OK
Running git apply with /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/patches/libxslt/0001-update-config.guess-and-config.sub-for-libxslt.patch... OK
Running 'configure' for libxslt 1.1.43... OK
Running 'compile' for libxslt 1.1.43... OK
Running 'install' for libxslt 1.1.43... OK
Activating libxslt 1.1.43 (from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/ports/x86_64-linux/libxslt/1.1.43)...
checking for whether -DNOKOGIRI_PACKAGED_LIBRARIES is accepted as CPPFLAGS... no
xml2-config cflags: -I/workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/ports/x86_64-linux/libxml2/2.13.6/include/libxml2
checking for whether -DNOKOGIRI_LIBXML2_PATCHES="\"0001-Remove-script-macro-support.patch 0002-Update-entities-to-remove-handling-of-ssi.patch 0009-allow-wildcard-namespaces.patch 0010-update-config.guess-and-config.sub-for-libxml2.patch 0011-rip-out-libxml2-s-libc_single_threaded-support.patch 0019-xpath-Use-separate-static-hash-table-for-standard-fu.patch\"" is accepted as CPPFLAGS... no
checking for -llzma... yes
xslt-config cflags: -I/workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/ports/x86_64-linux/libxml2/2.13.6/include/libxml2 -I/workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/ports/x86_64-linux/libxslt/1.1.43/include
checking for whether -DNOKOGIRI_LIBXSLT_PATCHES="\"0001-update-config.guess-and-config.sub-for-libxslt.patch\"" is accepted as CPPFLAGS... no
checking for xmlParseDoc() in libxml/parser.h... yes
checking for xsltParseStylesheetDoc() in libxslt/xslt.h... yes
checking for exsltFuncRegister() in libexslt/exslt.h... yes
Using mini_portile version 2.8.8
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libgumbo-1.0.0-nokogiri.
Configuration options: --disable-shared --enable-static CFLAGS\=-fPIC
Copying gumbo-parser files into tmp/x86_64-pc-linux/ports/libgumbo/1.0.0-nokogiri/gumbo-parser...
Running 'compile' for libgumbo 1.0.0-nokogiri... OK
Activating libgumbo 1.0.0-nokogiri (from ports/x86_64-linux/libgumbo/1.0.0-nokogiri)...
checking for whether -I/workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/ext/nokogiri/ports/x86_64-linux/libgumbo/1.0.0-nokogiri/include is accepted as CPPFLAGS... no
checking for gumbo_parse_with_options() in nokogiri_gumbo.h... yes
checking for xmlCtxtSetOptions()... yes
checking for xmlCtxtGetOptions()... no
checking for xmlSwitchEncodingName()... yes
checking for rb_category_warning()... yes
checking for whether -DNOKOGIRI_OTHER_LIBRARY_VERSIONS="\"libgumbo:1.0.0-nokogiri\"" is accepted as CPPFLAGS... no
creating Makefile

current directory: /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/ext/nokogiri
make DESTDIR\= sitearchdir\=./.gem.20250329-47811-w7yb9f sitelibdir\=./.gem.20250329-47811-w7yb9f clean

current directory: /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5/ext/nokogiri
make DESTDIR\= sitearchdir\=./.gem.20250329-47811-w7yb9f sitelibdir\=./.gem.20250329-47811-w7yb9f
compiling gumbo.c
warning: unknown warning option '-Wno-cast-function-type'; did you mean '-Wno-bad-function-cast'? [-Wunknown-warning-option]
gumbo.c:32:10: fatal error: 'nokogiri_gumbo.h' file not found
#include "nokogiri_gumbo.h"
         ^~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make: *** [Makefile:472: gumbo.o] Error 1

make failed, exit code 2

Gem files will remain installed in /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.5 for inspection.
Results logged to /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/extensions/x86_64-linux/3.3.0/nokogiri-1.18.5/gem_make.out

  /usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:51:in `block in make'
  /usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `each'
  /usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `make'
  /usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
  /usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/rubygems_gem_installer.rb:111:in `build_extensions'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/rubygems_gem_installer.rb:30:in `install'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/source/rubygems.rb:220:in `install'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/installer/gem_installer.rb:55:in `install'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/installer/gem_installer.rb:17:in `install_from_spec'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/installer/parallel_installer.rb:133:in `do_install'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/installer/parallel_installer.rb:124:in `block in worker_pool'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/worker.rb:62:in `apply_func'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/worker.rb:57:in `block in process_queue'
  <internal:kernel>:187:in `loop'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/worker.rb:54:in `process_queue'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing nokogiri (1.18.5), and Bundler cannot continue.

In Gemfile:
  github-pages was resolved to 228, which depends on
    jekyll-mentions was resolved to 1.6.0, which depends on
      html-pipeline was resolved to 2.14.3, which depends on
        nokogiri

/usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/installer/parallel_installer.rb:167:in `handle_error'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/installer/parallel_installer.rb:97:in `call'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/installer/parallel_installer.rb:66:in `call'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/installer.rb:198:in `install'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/installer.rb:84:in `block in run'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/rubygems_ext.rb:48:in `block in open_file_with_flock'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/rubygems_ext.rb:43:in `open'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/rubygems_ext.rb:43:in `open_file_with_flock'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/rubygems_ext.rb:54:in `open_file_with_lock'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/process_lock.rb:13:in `block in lock'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/shared_helpers.rb:105:in `filesystem_access'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/process_lock.rb:12:in `lock'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/installer.rb:71:in `run'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/installer.rb:23:in `install'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/cli/install.rb:72:in `run'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/cli.rb:247:in `block in install'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/settings.rb:159:in `temporary'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/cli.rb:246:in `install'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/vendor/thor/lib/thor.rb:538:in `dispatch'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/cli.rb:35:in `dispatch'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/cli.rb:29:in `start'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/exe/bundle:28:in `block in <top (required)>'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /usr/local/rvm/gems/ruby-3.3.4/gems/bundler-2.6.6/exe/bundle:20:in `<top (required)>'
  /usr/local/rvm/gems/ruby-3.3.4/bin/bundle:25:in `load'
  /usr/local/rvm/gems/ruby-3.3.4/bin/bundle:25:in `<main>'
  /usr/local/rvm/rubies/ruby-3.3.4/bin/ruby_executable_hooks:22:in `eval'
  /usr/local/rvm/rubies/ruby-3.3.4/bin/ruby_executable_hooks:22:in `<main>'
```

Signed-off-by: David Chamberlain <chaoscommencer@users.noreply.github.com>