Resolve jekyll build error
Command `bundle exec jekyll build --trace --verbose` results in an error indicating one of the following issues:
- `Fiber.current` is undefined
- method `[]` of `level` does not exist

Include logger dependency to resolve this error, detailed below:

```
bundler: failed to load command: jekyll (/workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/bin/jekyll)
/home/codespace/.rbenv/versions/3.3.0/lib/ruby/3.3.0/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/jekyll-3.9.3/lib/jekyll/log_adapter.rb:43:in `adjust_verbosity'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:27:in `process'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/jekyll-3.9.3/exe/jekyll:15:in `<top (required)>'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `load'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `<top (required)>'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `load'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:23:in `run'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/cli.rb:451:in `exec'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/cli.rb:34:in `dispatch'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/cli.rb:28:in `start'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/exe/bundle:28:in `block in <top (required)>'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /workspaces/StaticJekyllWebsiteTemplate-Public/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.5/exe/bundle:20:in `<top (required)>'
        from /home/codespace/.rbenv/versions/3.3.0/bin/bundle:25:in `load'
        from /home/codespace/.rbenv/versions/3.3.0/bin/bundle:25:in `<main>'
```

Signed-off-by: David Chamberlain <chaoscommencer@users.noreply.github.com>